version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - agent

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ./agent:/app
      - agent-data:/data

volumes:
  agent-data: