version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      agent:
        condition: service_healthy

  agent:
    build:
      context: ./agent
    ports:
      - "5001:5001"
    volumes:
      - ./agent:/app
      - agent-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  agent-data: