name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  agent-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r agent/requirements.txt
    - name: Check for outdated python dependencies
      run: |
        pip list --outdated
    - name: Lint with ruff
      run: |
        ruff --output-format=github .
    - name: Format with ruff
      run: |
        ruff format --check .
    - name: Type check with pyright
      run: |
        pyright

  client-and-server-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install client dependencies
      run: npm install
      working-directory: ./client
    - name: Install server dependencies
      run: npm install
      working-directory: ./server
    - name: Check for outdated client dependencies
      run: npm outdated
      working-directory: ./client
    - name: Check for outdated server dependencies
      run: npm outdated
      working-directory: ./server
    - name: Check client formatting
      run: npm run format
      working-directory: ./client
    - name: Check server formatting
      run: npm run format
      working-directory: ./server
    - name: Type-check client
      run: npm run type-check
      working-directory: ./client
    - name: Build client
      run: npm run build
      working-directory: ./client
    - name: Build server
      run: npm run build
      working-directory: ./server